### PR TITLE
Frontend Integration and Function Enhancements

### PR DESCRIPTION
**Pull request by Anshu370**
Hey @Vikranth3140 

Solved all the major conflicts in branches.

->Frontend completed and successfully connected with script.py.
->Modified the encrypt_file and decrypt_file functions to handle both GUI and CLI functionality for smoother user experience.
->Ensured compatibility between the two interfaces.

### CODE REVIEW

**Comment by Anshu370** [comment]
Here Is Image
-> 
image

**Review by Vikranth3140 — CHANGES_REQUESTED** [review]
Everything is good to go

Just one small enhancement:

Initialise the `secret.key` in the root directory instead of `Frontend` Directory

**Review by Anshu370 — COMMENTED** [review]
Changes Implemented.

**Comment by Anshu370** [comment]
Hey @Vikranth3140 

I had solved that Directory Issue.

**Review by Vikranth3140 — APPROVED** [review]
Lgtm

**Comment by Vikranth3140** [comment]
Hey @Anshu370,

Perfect, Thanks for implementing all the requested changes.
Merging the PR.

Congratulations on your first accepted PR🎉!
Please head over to https://hacktoberfest.com and claim your merged PR as we are registered under Hacktoberfest 2024

Additionally do checkout my other repos under `hacktoberfest` label - [Repos](https://github.com/Vikranth3140?tab=repositories&q=&type=&language=&sort=)

**Comment by Vikranth3140** [comment]
Also, @Anshu370 is it possible to include the GUI part in the README.
Would be helpful :)

**Pull request merged**
